<img src="img/logo.png">

# Chargement des librairies

In [1]:
import numpy as np
import pandas as pd
from mylib.fonction_exploration import exploration
import warnings
warnings.filterwarnings('ignore')

print("Version numpy : " + np.__version__)
print("Version pandas : " + pd.__version__)

chemin_erp = 'src/erp.xlsx'
chemin_liaison = 'src/liaison.xlsx'
chemin_web = 'src/web.xlsx'

Version numpy : 1.23.5
Version pandas : 1.4.4

# Chargement des fichiers

In [2]:
erp = pd.read_excel(chemin_erp)
liaison = pd.read_excel(chemin_liaison)
web = pd.read_excel(chemin_web)

# Utilisation de la fonction exploration

## Fichier **erp**.xlsx

In [3]:
exploration(erp)

--------------------------
Aperçu du DataFrame (head)
--------------------------

   product_id  onsale_web  price  stock_quantity stock_status
0        3847           1   24.2               0   outofstock
1        3849           1   34.3               0   outofstock
2        3850           1   20.8               0   outofstock
3        4032           1   14.1               0   outofstock
4        4039           1   46.0               0   outofstock

------------------------------------
Aperçu de la fin du DataFrame (tail)
------------------------------------

     product_id  onsale_web  price  stock_quantity stock_status
820        7203           0   45.0              30      instock
821        7204           0   45.0               9      instock
822        7247           1   54.8              23      instock
823        7329           0   26.5              14      instock
824        7338           1   16.3              45      instock

---------------------------------
Échantillon du DataFrame (sample)
---------------------------------

     product_id  onsale_web  price  stock_quantity stock_status
317        4690           1   12.8              15      instock
535        5548           1   48.8               6      instock
561        5617           1   27.8              12      instock
556        5612           1  124.8              12      instock
276        4633           1   52.4               2      instock

---------------------------------------
Nombre de lignes et de colonnes (shape)
---------------------------------------

(825, 5)

-------------------------
Type des données (dtypes)
-------------------------

product_id          int64
onsale_web          int64
price             float64
stock_quantity      int64
stock_status       object
dtype: object

------------
Infos (info)
------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      825 non-null    int64
 1   onsale_web      825 non-null    int64
 2   price           825 non-null    float64
 3   stock_quantity  825 non-null    int64
 4   stock_status    825 non-null    object
dtypes: float64(1), int64(3), object(1)
memory usage: 32.4+ KB
None

----------------------------
Nombre de NaN (isna().sum())
----------------------------

product_id        0
onsale_web        0
price             0
stock_quantity    0
stock_status      0
dtype: int64

--------------------------------------
Affichage des Nan (isna().any(axis=1))
--------------------------------------

Empty DataFrame
Columns: [product_id, onsale_web, price, stock_quantity, stock_status]
Index: []

---------------------------------------
Nombre de doublons (duplicated().sum())
---------------------------------------

0

-----------------------------------------------------
Affichage des doublons (df[df.duplicated()].head(10))
-----------------------------------------------------

Empty DataFrame
Columns: [product_id, onsale_web, price, stock_quantity, stock_status]
Index: []

-----------------------------------
Résumé analyse univariée (describe)
-----------------------------------

         product_id  onsale_web       price  stock_quantity stock_status
count    825.000000  825.000000  825.000000      825.000000          825
unique          NaN         NaN         NaN             NaN            2
top             NaN         NaN         NaN             NaN      instock
freq            NaN         NaN         NaN             NaN          638
mean    5162.597576    0.869091   32.415636       26.496970          NaN
std      902.644635    0.337506   26.795849       45.892422          NaN
min     3847.000000    0.000000    5.200000        0.000000          NaN
25%     4348.000000    1.000000   14.600000        1.000000          NaN
50%     4907.000000    1.000000   24.400000       11.000000          NaN
75%     5805.000000    1.000000   42.000000       34.000000          NaN
max     7338.000000    1.000000  225.000000      578.000000          NaN

### Remarques sur le fichier erp.xlsx

1. Aucune valeur nulle
2. Pas de doublons
3. Tous les formats de données sont corrects
4. Prix moyen de 32.42 euros et prix max de 225 euros
5. Stock moyen de 26.5 et stock max de 578 par product_id

## Fichier **liaison**.xlsx

In [4]:
exploration(liaison)

--------------------------
Aperçu du DataFrame (head)
--------------------------

   product_id id_web
0        3847  15298
1        3849  15296
2        3850  15300
3        4032  19814
4        4039  19815

------------------------------------
Aperçu de la fin du DataFrame (tail)
------------------------------------

     product_id   id_web
820        7203      NaN
821        7204      NaN
822        7247  13127-1
823        7329  14680-1
824        7338    16230

---------------------------------
Échantillon du DataFrame (sample)
---------------------------------

     product_id id_web
712        6216  15070
752        6632  15794
9          4045  16041
715        6223  15324
772        6898    NaN

---------------------------------------
Nombre de lignes et de colonnes (shape)
---------------------------------------

(825, 2)

-------------------------
Type des données (dtypes)
-------------------------

product_id     int64
id_web        object
dtype: object

------------
Infos (info)
------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  825 non-null    int64
 1   id_web      734 non-null    object
dtypes: int64(1), object(1)
memory usage: 13.0+ KB
None

----------------------------
Nombre de NaN (isna().sum())
----------------------------

product_id     0
id_web        91
dtype: int64

--------------------------------------
Affichage des Nan (isna().any(axis=1))
--------------------------------------

     product_id id_web
19         4055    NaN
49         4090    NaN
50         4092    NaN
119        4195    NaN
131        4209    NaN
..          ...    ...
817        7196    NaN
818        7200    NaN
819        7201    NaN
820        7203    NaN
821        7204    NaN

[91 rows x 2 columns]

---------------------------------------
Nombre de doublons (duplicated().sum())
---------------------------------------

0

-----------------------------------------------------
Affichage des doublons (df[df.duplicated()].head(10))
-----------------------------------------------------

Empty DataFrame
Columns: [product_id, id_web]
Index: []

-----------------------------------
Résumé analyse univariée (describe)
-----------------------------------

         product_id   id_web
count    825.000000    734.0
unique          NaN    734.0
top             NaN  15298.0
freq            NaN      1.0
mean    5162.597576      NaN
std      902.644635      NaN
min     3847.000000      NaN
25%     4348.000000      NaN
50%     4907.000000      NaN
75%     5805.000000      NaN
max     7338.000000      NaN

### Remarques sur le fichier liaison.xlsx

1. 91 valeurs nulles dans id_web
2. Pas de doublons
3. Tous les formats de données sont corrects

## Fichier **web**.xlsx

In [5]:
exploration(web)

--------------------------
Aperçu du DataFrame (head)
--------------------------

                   sku  virtual  downloadable  rating_count  average_rating  \
0  bon-cadeau-25-euros        0             0             0             0.0
1                15298        0             0             0             0.0
2                15296        0             0             0             0.0
3                15300        0             0             0             0.0
4                19814        0             0             0             0.0

   total_sales tax_status  tax_class  post_author           post_date  ...  \
0         10.0    taxable        NaN          1.0 2018-06-01 13:53:46  ...
1          6.0    taxable        NaN          2.0 2018-02-08 12:58:52  ...
2          0.0    taxable        NaN          2.0 2018-02-08 13:49:41  ...
3          0.0    taxable        NaN          2.0 2018-02-08 14:08:36  ...
4          3.0    taxable        NaN          2.0 2018-02-09 14:01:05  ...

                                           post_name       post_modified  \
0                             bon-cadeau-de-25-euros 2018-06-01 14:13:57
1        pierre-jean-villa-saint-joseph-preface-2018 2019-12-30 09:30:29
2          pierre-jean-villa-saint-joseph-tilde-2017 2019-12-21 09:00:17
3  pierre-jean-villa-croze-hermitage-accroche-coe... 2020-06-26 18:15:03
4                  pierre-jean-villa-igp-gamine-2018 2020-01-04 16:36:01

    post_modified_gmt post_content_filtered post_parent  \
0 2018-06-01 12:13:57                   NaN         0.0
1 2019-12-30 08:30:29                   NaN         0.0
2 2019-12-21 08:00:17                   NaN         0.0
3 2020-06-26 16:15:03                   NaN         0.0
4 2020-01-04 15:36:01                   NaN         0.0

                                                guid menu_order  post_type  \
0  https://www.bottle-neck.fr/?post_type=product&...        0.0    product
1  https://www.bottle-neck.fr/?post_type=product&...        0.0    product
2  https://www.bottle-neck.fr/?post_type=product&...        0.0    product
3  https://www.bottle-neck.fr/?post_type=product&...        0.0    product
4  https://www.bottle-neck.fr/?post_type=product&...        0.0    product

  post_mime_type comment_count
0            NaN           0.0
1            NaN           0.0
2            NaN           0.0
3            NaN           0.0
4            NaN           0.0

[5 rows x 28 columns]

------------------------------------
Aperçu de la fin du DataFrame (tail)
------------------------------------

          sku  virtual  downloadable  rating_count  average_rating  \
1508    16135        0             0             0             0.0
1509    15891        0             0             0             0.0
1510    15887        0             0             0             0.0
1511  13127-1        0             0             0             0.0
1512    16230        0             0             0             0.0

      total_sales tax_status  tax_class  post_author           post_date  ...  \
1508          5.0        NaN        NaN          2.0 2020-04-25 13:22:38  ...
1509          0.0        NaN        NaN          2.0 2020-05-02 14:53:40  ...
1510          0.0        NaN        NaN          2.0 2020-05-02 15:00:54  ...
1511          0.0        NaN        NaN          2.0 2020-06-09 15:42:04  ...
1512          0.0        NaN        NaN          2.0 2020-07-20 11:00:00  ...

                                              post_name       post_modified  \
1508                    mouthes-le-bihan-aime-chai-2015 2020-08-26 17:35:03
1509         camin-larredya-jurancon-sec-la-virada-2018 2020-08-26 17:35:02
1510             jamet-cote-rotie-fructus-voluptas-2018 2020-08-14 18:15:03
1511     clos-du-mont-olivet-chateauneuf-du-pape-2007-2 2020-07-20 17:09:06
1512  domaine-saint-nicolas-fiefs-vendeens-blanc-les... 2020-08-13 10:45:03

       post_modified_gmt post_content_filtered post_parent  \
1508 2020-08-26 15:35:03                   NaN         0.0
1509 2020-08-26 15:35:02                   NaN         0.0
1510 2020-08-14 16:15:03                   NaN         0.0
1511 2020-07-20 15:09:06                   NaN         0.0
1512 2020-08-13 08:45:03                   NaN         0.0

                                                   guid menu_order  \
1508  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1509  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1510  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1511  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1512  https://www.bottle-neck.fr/wp-content/uploads/...        0.0

       post_type post_mime_type comment_count
1508  attachment     image/jpeg           0.0
1509  attachment     image/jpeg           0.0
1510  attachment     image/jpeg           0.0
1511  attachment     image/jpeg           0.0
1512  attachment     image/jpeg           0.0

[5 rows x 28 columns]

---------------------------------
Échantillon du DataFrame (sample)
---------------------------------

        sku  virtual  downloadable  rating_count  average_rating  total_sales  \
766     NaN        0             0             0             NaN          NaN
692   15161        0             0             0             0.0          0.0
1099  13659        0             0             0             0.0          0.0
971   13460        0             0             0             0.0          0.0
228   15621        0             0             0             0.0         19.0

     tax_status  tax_class  post_author           post_date  ...  \
766         NaN        NaN          NaN                 NaT  ...
692     taxable        NaN          2.0 2019-07-30 14:59:19  ...
1099        NaN        NaN          2.0 2018-04-17 17:12:30  ...
971         NaN        NaN          2.0 2018-02-27 13:17:25  ...
228     taxable        NaN          2.0 2018-04-12 09:51:40  ...

                                              post_name       post_modified  \
766                                                 NaN                 NaT
692   le-pas-de-lescalette-terrasses-du-larzac-pas-d... 2020-02-10 09:30:09
1099   domaine-plageoles-vin-de-france-contre-pied-2016 2020-08-26 17:35:02
971       domaine-serol-cote-roannaise-perdriziere-2016 2020-07-01 18:55:02
228               domaine-giudicelli-vfd-ete-rouge-2018 2020-08-27 10:12:06

       post_modified_gmt post_content_filtered post_parent  \
766                  NaT                   NaN         NaN
692  2020-02-10 08:30:09                   NaN         0.0
1099 2020-08-26 15:35:02                   NaN         0.0
971  2020-07-01 16:55:02                   NaN         0.0
228  2020-08-27 08:12:06                   NaN         0.0

                                                   guid menu_order  \
766                                                 NaN        NaN
692   https://www.bottle-neck.fr/?post_type=product&...        0.0
1099  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
971   https://www.bottle-neck.fr/wp-content/uploads/...        0.0
228   https://www.bottle-neck.fr/?post_type=product&...        0.0

       post_type post_mime_type comment_count
766          NaN            NaN           NaN
692      product            NaN           0.0
1099  attachment     image/jpeg           0.0
971   attachment     image/jpeg           0.0
228      product            NaN           0.0

[5 rows x 28 columns]

---------------------------------------
Nombre de lignes et de colonnes (shape)
---------------------------------------

(1513, 28)

-------------------------
Type des données (dtypes)
-------------------------

sku                              object
virtual                           int64
downloadable                      int64
rating_count                      int64
average_rating                  float64
total_sales                     float64
tax_status                       object
tax_class                       float64
post_author                     float64
post_date                datetime64[ns]
post_date_gmt            datetime64[ns]
post_content                    float64
post_title                       object
post_excerpt                     object
post_status                      object
comment_status                   object
ping_status                      object
post_password                   float64
post_name                        object
post_modified            datetime64[ns]
post_modified_gmt        datetime64[ns]
post_content_filtered           float64
post_parent                     float64
guid                             object
menu_order                      float64
post_type                        object
post_mime_type                   object
comment_count                   float64
dtype: object

------------
Infos (info)
------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    1428 non-null   object
 1   virtual                1513 non-null   int64
 2   downloadable           1513 non-null   int64
 3   rating_count           1513 non-null   int64
 4   average_rating         1430 non-null   float64
 5   total_sales            1430 non-null   float64
 6   tax_status             716 non-null    object
 7   tax_class              0 non-null      float64
 8   post_author            1430 non-null   float64
 9   post_date              1430 non-null   datetime64[ns]
 10  post_date_gmt          1430 non-null   datetime64[ns]
 11  post_content           0 non-null      float64
 12  post_title             1430 non-null   object
 13  post_excerpt           716 non-null    object
 14  post_status            1430 non-null   object
 15  comment_status         1430 non-null   object
 16  ping_status            1430 non-null   object
 17  post_password          0 non-null      float64
 18  post_name              1430 non-null   object
 19  post_modified          1430 non-null   datetime64[ns]
 20  post_modified_gmt      1430 non-null   datetime64[ns]
 21  post_content_filtered  0 non-null      float64
 22  post_parent            1430 non-null   float64
 23  guid                   1430 non-null   object
 24  menu_order             1430 non-null   float64
 25  post_type              1430 non-null   object
 26  post_mime_type         714 non-null    object
 27  comment_count          1430 non-null   float64
dtypes: datetime64[ns](4), float64(10), int64(3), object(11)
memory usage: 331.1+ KB
None

----------------------------
Nombre de NaN (isna().sum())
----------------------------

sku                        85
virtual                     0
downloadable                0
rating_count                0
average_rating             83
total_sales                83
tax_status                797
tax_class                1513
post_author                83
post_date                  83
post_date_gmt              83
post_content             1513
post_title                 83
post_excerpt              797
post_status                83
comment_status             83
ping_status                83
post_password            1513
post_name                  83
post_modified              83
post_modified_gmt          83
post_content_filtered    1513
post_parent                83
guid                       83
menu_order                 83
post_type                  83
post_mime_type            799
comment_count              83
dtype: int64

--------------------------------------
Affichage des Nan (isna().any(axis=1))
--------------------------------------

                      sku  virtual  downloadable  rating_count  \
0     bon-cadeau-25-euros        0             0             0
1                   15298        0             0             0
2                   15296        0             0             0
3                   15300        0             0             0
4                   19814        0             0             0
...                   ...      ...           ...           ...
1508                16135        0             0             0
1509                15891        0             0             0
1510                15887        0             0             0
1511              13127-1        0             0             0
1512                16230        0             0             0

      average_rating  total_sales tax_status  tax_class  post_author  \
0                0.0         10.0    taxable        NaN          1.0
1                0.0          6.0    taxable        NaN          2.0
2                0.0          0.0    taxable        NaN          2.0
3                0.0          0.0    taxable        NaN          2.0
4                0.0          3.0    taxable        NaN          2.0
...              ...          ...        ...        ...          ...
1508             0.0          5.0        NaN        NaN          2.0
1509             0.0          0.0        NaN        NaN          2.0
1510             0.0          0.0        NaN        NaN          2.0
1511             0.0          0.0        NaN        NaN          2.0
1512             0.0          0.0        NaN        NaN          2.0

               post_date  ...  \
0    2018-06-01 13:53:46  ...
1    2018-02-08 12:58:52  ...
2    2018-02-08 13:49:41  ...
3    2018-02-08 14:08:36  ...
4    2018-02-09 14:01:05  ...
...                  ...  ...
1508 2020-04-25 13:22:38  ...
1509 2020-05-02 14:53:40  ...
1510 2020-05-02 15:00:54  ...
1511 2020-06-09 15:42:04  ...
1512 2020-07-20 11:00:00  ...

                                              post_name       post_modified  \
0                                bon-cadeau-de-25-euros 2018-06-01 14:13:57
1           pierre-jean-villa-saint-joseph-preface-2018 2019-12-30 09:30:29
2             pierre-jean-villa-saint-joseph-tilde-2017 2019-12-21 09:00:17
3     pierre-jean-villa-croze-hermitage-accroche-coe... 2020-06-26 18:15:03
4                     pierre-jean-villa-igp-gamine-2018 2020-01-04 16:36:01
...                                                 ...                 ...
1508                    mouthes-le-bihan-aime-chai-2015 2020-08-26 17:35:03
1509         camin-larredya-jurancon-sec-la-virada-2018 2020-08-26 17:35:02
1510             jamet-cote-rotie-fructus-voluptas-2018 2020-08-14 18:15:03
1511     clos-du-mont-olivet-chateauneuf-du-pape-2007-2 2020-07-20 17:09:06
1512  domaine-saint-nicolas-fiefs-vendeens-blanc-les... 2020-08-13 10:45:03

       post_modified_gmt post_content_filtered post_parent  \
0    2018-06-01 12:13:57                   NaN         0.0
1    2019-12-30 08:30:29                   NaN         0.0
2    2019-12-21 08:00:17                   NaN         0.0
3    2020-06-26 16:15:03                   NaN         0.0
4    2020-01-04 15:36:01                   NaN         0.0
...                  ...                   ...         ...
1508 2020-08-26 15:35:03                   NaN         0.0
1509 2020-08-26 15:35:02                   NaN         0.0
1510 2020-08-14 16:15:03                   NaN         0.0
1511 2020-07-20 15:09:06                   NaN         0.0
1512 2020-08-13 08:45:03                   NaN         0.0

                                                   guid menu_order  \
0     https://www.bottle-neck.fr/?post_type=product&...        0.0
1     https://www.bottle-neck.fr/?post_type=product&...        0.0
2     https://www.bottle-neck.fr/?post_type=product&...        0.0
3     https://www.bottle-neck.fr/?post_type=product&...        0.0
4     https://www.bottle-neck.fr/?post_type=product&...        0.0
...                                                 ...        ...
1508  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1509  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1510  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1511  https://www.bottle-neck.fr/wp-content/uploads/...        0.0
1512  https://www.bottle-neck.fr/wp-content/uploads/...        0.0

       post_type post_mime_type comment_count
0        product            NaN           0.0
1        product            NaN           0.0
2        product            NaN           0.0
3        product            NaN           0.0
4        product            NaN           0.0
...          ...            ...           ...
1508  attachment     image/jpeg           0.0
1509  attachment     image/jpeg           0.0
1510  attachment     image/jpeg           0.0
1511  attachment     image/jpeg           0.0
1512  attachment     image/jpeg           0.0

[1513 rows x 28 columns]

---------------------------------------
Nombre de doublons (duplicated().sum())
---------------------------------------

82

-----------------------------------------------------
Affichage des doublons (df[df.duplicated()].head(10))
-----------------------------------------------------

     sku  virtual  downloadable  rating_count  average_rating  total_sales  \
179  NaN        0             0             0             NaN          NaN
227  NaN        0             0             0             NaN          NaN
230  NaN        0             0             0             NaN          NaN
231  NaN        0             0             0             NaN          NaN
233  NaN        0             0             0             NaN          NaN
237  NaN        0             0             0             NaN          NaN
283  NaN        0             0             0             NaN          NaN
309  NaN        0             0             0             NaN          NaN
310  NaN        0             0             0             NaN          NaN
311  NaN        0             0             0             NaN          NaN

    tax_status  tax_class  post_author post_date  ... post_name  \
179        NaN        NaN          NaN       NaT  ...       NaN
227        NaN        NaN          NaN       NaT  ...       NaN
230        NaN        NaN          NaN       NaT  ...       NaN
231        NaN        NaN          NaN       NaT  ...       NaN
233        NaN        NaN          NaN       NaT  ...       NaN
237        NaN        NaN          NaN       NaT  ...       NaN
283        NaN        NaN          NaN       NaT  ...       NaN
309        NaN        NaN          NaN       NaT  ...       NaN
310        NaN        NaN          NaN       NaT  ...       NaN
311        NaN        NaN          NaN       NaT  ...       NaN

     post_modified post_modified_gmt post_content_filtered post_parent guid  \
179            NaT               NaT                   NaN         NaN  NaN
227            NaT               NaT                   NaN         NaN  NaN
230            NaT               NaT                   NaN         NaN  NaN
231            NaT               NaT                   NaN         NaN  NaN
233            NaT               NaT                   NaN         NaN  NaN
237            NaT               NaT                   NaN         NaN  NaN
283            NaT               NaT                   NaN         NaN  NaN
309            NaT               NaT                   NaN         NaN  NaN
310            NaT               NaT                   NaN         NaN  NaN
311            NaT               NaT                   NaN         NaN  NaN

    menu_order  post_type post_mime_type comment_count
179        NaN        NaN            NaN           NaN
227        NaN        NaN            NaN           NaN
230        NaN        NaN            NaN           NaN
231        NaN        NaN            NaN           NaN
233        NaN        NaN            NaN           NaN
237        NaN        NaN            NaN           NaN
283        NaN        NaN            NaN           NaN
309        NaN        NaN            NaN           NaN
310        NaN        NaN            NaN           NaN
311        NaN        NaN            NaN           NaN

[10 rows x 28 columns]

-----------------------------------
Résumé analyse univariée (describe)

### Remarques sur le fichier web.xlsx

1. Beaucoup de valeurs nulles, seules les colonnes "virtual", "downloadable" et "rating_count" n'en ont pas
2. 82 doublons
3. Tous les formats de données sont corrects